# Generated by Django 5.2 on 2026-08-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_users', '0002_alter_demoaccount_options_alter_demoorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('direction', models.CharField(choices=[('ABOVE', 'Выше'), ('BELOW', 'Ниже')], max_length=10)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ценовое уведомление',
                'verbose_name_plural': 'Ценовые уведомления',
            },
        ),
        migrations.CreateModel(
            name='TradingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Всего сделок')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общий объем (USDT)')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая прибыль (USDT)')),
                ('win_rate', models.FloatField(default=0.0, verbose_name='Процент побед')),
                ('profit_factor', models.FloatField(default=0.0, verbose_name='Фактор прибыли')),
                ('sharpe_ratio', models.FloatField(default=0.0, verbose_name='Коэффициент Шарпа')),
                ('best_trade', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Лучшая сделка (USDT)')),
                ('worst_trade', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Худшая сделка (USDT)')),
                ('avg_trade_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Средняя прибыль (USDT)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='App_users.demoaccount')),
            ],
            options={
                'verbose_name': 'Статистика торговли',
                'verbose_name_plural': 'Статистика торговли',
            },
        ),
    ]
