# Generated by Django 5.2 on 2026-08-28 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название стратегии')),
                ('symbol', models.CharField(max_length=20, verbose_name='Торговая пара')),
                ('strategy_type', models.CharField(choices=[('RSI', 'RSI'), ('MACD', 'MACD'), ('BOLLINGER', 'Bollinger Bands'), ('COMPOSITE', 'Композитная')], max_length=20, verbose_name='Тип стратегии')),
                ('params', models.JSONField(default=dict, help_text='JSON с параметрами (period, threshold и т.д.)', verbose_name='Параметры стратегии')),
                ('timeframe', models.CharField(default='1h', max_length=10, verbose_name='Таймфрейм')),
                ('period_days', models.IntegerField(default=30, verbose_name='Период (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стратегия для бэктестинга',
                'verbose_name_plural': 'Стратегии для бэктестинга',
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Всего сделок')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Прибыльных')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Убыточных')),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая доходность (%)')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимальная просадка (%)')),
                ('sharpe_ratio', models.FloatField(default=0, verbose_name='Коэффициент Шарпа')),
                ('win_rate', models.FloatField(default=0, verbose_name='Процент побед')),
                ('equity_curve', models.JSONField(default=list, verbose_name='Кривая эквити')),
                ('trades_log', models.JSONField(default=list, verbose_name='Журнал сделок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='App_analytics.backteststrategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Результат бэктестинга',
                'verbose_name_plural': 'Результаты бэктестинга',
            },
        ),
        migrations.CreateModel(
            name='TradeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Общая стоимость портфеля')),
                ('balance', models.JSONField(default=dict, verbose_name='Баланс на момент снимка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Снимок портфеля',
                'verbose_name_plural': 'Снимки портфеля',
                'ordering': ['-created_at'],
            },
        ),
    ]
