# Generated by Django 5.2 on 2026-08-27 19:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.JSONField(default=dict)),
                ('total_value_usdt', models.DecimalField(decimal_places=2, default=0, help_text='Общая стоимость портфеля в USDT', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Демо-счет',
                'verbose_name_plural': 'Демо-счета',
            },
        ),
        migrations.CreateModel(
            name='DemoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Торговая пара, например BTC/USDT', max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], max_length=4)),
                ('order_type', models.CharField(choices=[('MARKET', 'Рыночный'), ('LIMIT', 'Лимитный')], default='MARKET', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=8, help_text='Для лимитных ордеров', max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('FILLED', 'Исполнен'), ('CANCELLED', 'Отменен')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='App_users.demoaccount')),
            ],
            options={
                'verbose_name': 'Демо-ордер',
                'verbose_name_plural': 'Демо-ордера',
            },
        ),
    ]
