# Generated by Django 5.2 on 2026-08-28 10:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demoaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Демо-счет', 'verbose_name_plural': 'Демо-счета'},
        ),
        migrations.AlterModelOptions(
            name='demoorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Демо-ордер', 'verbose_name_plural': 'Демо-ордера'},
        ),
        migrations.AddField(
            model_name='demoaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Можно ли использовать демо-счет', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='demoorder',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='demoaccount',
            name='balance',
            field=models.JSONField(default=dict, help_text='{"USDT": 100000.0, "BTC": 0.0}', verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='demoaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='demoaccount',
            name='total_value_usdt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая стоимость портфеля в USDT', max_digits=20, verbose_name='Общая стоимость (USDT)'),
        ),
        migrations.AlterField(
            model_name='demoaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='demoaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='App_users.demoaccount', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Исполнен'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Исполнено'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Рыночный'), ('LIMIT', 'Лимитный')], default='MARKET', max_length=10, verbose_name='Тип ордера'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Для лимитных ордеров', max_digits=20, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], max_length=4, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыт'), ('FILLED', 'Исполнен'), ('CANCELLED', 'Отменен'), ('REJECTED', 'Отклонен')], default='OPEN', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='demoorder',
            name='symbol',
            field=models.CharField(help_text='Например BTC/USDT', max_length=20, verbose_name='Торговая пара'),
        ),
    ]
