# Generated by Django 5.2 on 2026-08-28 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_users', '0002_alter_demoaccount_options_alter_demoorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demoorder',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Цена стоп-лосс', max_digits=20, null=True, verbose_name='Stop Loss'),
        ),
        migrations.AddField(
            model_name='demoorder',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Цена тейк-профит', max_digits=20, null=True, verbose_name='Take Profit'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Например BTC/USDT', max_length=20, verbose_name='Торговая пара')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список отслеживания',
                'verbose_name_plural': 'Списки отслеживания',
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
