# Generated by Django 5.2 on 2026-08-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_users', '0003_demoorder_stop_loss_demoorder_take_profit_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.JSONField(default=dict, help_text='{"USDT": 0.0, "BTC": 0.0}', verbose_name='Баланс')),
                ('total_value_usdt', models.DecimalField(decimal_places=2, default=0, help_text='Общая стоимость портфеля в USDT', max_digits=20, verbose_name='Общая стоимость (USDT)')),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли использовать реальный счёт', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реальный счёт',
                'verbose_name_plural': 'Реальные счета',
                'ordering': ['-created_at'],
            },
        ),
    ]
