# Generated by Django 5.2 on 2026-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_users', '0004_realaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoorder',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Цена входа'),
        ),
        migrations.AddField(
            model_name='demoorder',
            name='expiration_time',
            field=models.DateTimeField(blank=True, help_text='Когда сделка должна быть закрыта', null=True, verbose_name='Время экспирации'),
        ),
        migrations.AddField(
            model_name='demoorder',
            name='trade_direction',
            field=models.CharField(blank=True, choices=[('CALL', 'Вверх'), ('PUT', 'Вниз')], max_length=4, null=True, verbose_name='Направление сделки'),
        ),
        migrations.AddField(
            model_name='demoorder',
            name='trade_duration',
            field=models.IntegerField(default=0, help_text='Длительность бинарной сделки в секундах', verbose_name='Длительность сделки (сек)'),
        ),
    ]
